### ISSUE TITLE
Pouvoir du rouge

### ISSUE THREAD

**Issue by BourgoisMickael** [nlehir/phantom_opera#8]
Dans les règles le rouge ne peut utiliser son pouvoir qu'après s'être déplacé alors que sur le serveur il peut activer son pouvoir avant ou après s'être déplacé. Aussi le serveur ne notifie pas les clients du personnage innocenté ou de la carte tiré.

**Comment by nlehir** [comment]
Le temps d'utilisation du pouvoir a été corrigé dans fix/red_power.
Le personnage innocenté peut-être déduit de la variable game_state au step suivant.
